# Generated by Django 5.1.3 on 2024-11-30 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_address_geo_alter_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='geo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.geo'),
        ),
        migrations.AlterField(
            model_name='address',
            name='suite',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='geo',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='geo',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
