# Generated by Django 5.1.3 on 2024-11-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_address_geo_alter_address_suite_alter_geo_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geo',
            name='lat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='geo',
            name='lng',
            field=models.CharField(max_length=100),
        ),
    ]
